name: Metrics
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: GitHub stargazers graph
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.stargazers.graph.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts_type: graph
          plugin_stargazers_days: 30
